# -*- coding: utf-8 -*-
"""TrainDataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SEoUewl_qm43ozeO0QFLL8MoSOILOHmw
"""

from google.colab import drive
drive.mount('/content/drive')

# Download repo of dataset here.

# Commented out IPython magic to ensure Python compatibility.
#clone YOLOv5 and 
!git clone https://github.com/ultralytics/yolov5  # clone repo

from IPython.display import Image, clear_output

!python train.py --img 416 --batch 16 --epochs 1001 --data /content/majorChess/coco.yaml --weights yolov5m.pt --cache --save-period 500 --project /content/drive/MyDrive/robotics --name DetectionH --hyp /content/yolov5/data/hyps/hyp.scratch-high.yaml

!python val.py --weights /content/drive/MyDrive/robotics/DetectionH5/weights/best.pt --data /content/majorChess/coco.yaml --img 416 --iou 0.65 --half --task test
